name: sahabat_rs
description: Aplikasi SahabatRS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependensi Utama
  supabase_flutter: ^2.10.3
  flutter_svg: ^2.0.11

  # Hapus baris intl ini, biarkan flutter_localizations yang mengaturnya
  intl: ^0.20.2

  # Dependensi Lokalisasi (Penting untuk intl/tanggal)
  flutter_localizations:
    sdk: flutter

  # OpenStreetMap
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Aset Gambar & Icon
  assets:
    - assets/images/
    - assets/images/penjadwalan/
    - assets/icons/
